-- AlterTable
ALTER TABLE "Devis" ADD COLUMN     "activites" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "ados" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "adultes" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "budgetMax" DECIMAL(10,2),
ADD COLUMN     "budgetMin" DECIMAL(10,2),
ADD COLUMN     "dateDebutSouhaitee" TIMESTAMP(3),
ADD COLUMN     "dateFinSouhaitee" TIMESTAMP(3),
ADD COLUMN     "dureeFlexible" BOOLEAN DEFAULT false,
ADD COLUMN     "enfants" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "enfantsAge" TEXT,
ADD COLUMN     "newsletter" BOOLEAN DEFAULT false,
ADD COLUMN     "nom" TEXT,
ADD COLUMN     "prenom" TEXT,
ADD COLUMN     "regime" TEXT,
ADD COLUMN     "regimePrecision" TEXT,
ADD COLUMN     "regionIds" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "source" TEXT,
ADD COLUMN     "telephone" TEXT,
ADD COLUMN     "themeIds" INTEGER[] DEFAULT ARRAY[]::INTEGER[],
ADD COLUMN     "transport" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "typeHebergement" TEXT,
ADD COLUMN     "typeVoyage" TEXT[] DEFAULT ARRAY[]::TEXT[];
